package azure.lane.solutions.FindTheDifference;

/**
 * @author Zheyuan Fu
 * @date 2019.04.30
 */
public class FindTheDifference {
    /**
     * Given two strings s and t which consist of only lowercase letters.
     *
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     *
     * Find the letter that was added in t.
     *
     * Example:
     *
     * Input:
     * s = "abcd"
     * t = "abcde"
     *
     * Output:
     * e
     *
     * Explanation:
     * 'e' is the letter that was added.
     * */
    public char findTheDifference(String s, String t) {
        char val = 0;
        for(int i = 0; i < s.length(); i ++) {
            val ^= s.charAt(i);
            val ^= t.charAt(i);
        }
        val ^= t.charAt(t.length() - 1);
        return val;
    }
}
